# Generated by Django 2.2.7 on 2019-11-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailIngredientUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=1.0)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cocktail')),
            ],
        ),
    ]
